In [1]:
# Student records using Dictionary, Tuple and List

students = {
    101: ("Rahul", "CSE", 85),
    102: ("Amit", "IT", 78),
    103: ("Sneha", "ENTC", 90)}

# Add a new student
students[104] = ("Priya", "CSE", 88)

# Delete an existing student
del students[102]

# Update details of a student
students[103] = ("Sneha", "CSE", 95)

# Display final student records
print("Final Student Records:")

for roll_no, details in students.items():
    print("Roll No:", roll_no)
    print("Name:", details[0])
    print("Branch:", details[1])
    print("Marks:", details[2])
    print()

Final Student Records:
Roll No: 101
Name: Rahul
Branch: CSE
Marks: 85

Roll No: 103
Name: Sneha
Branch: CSE
Marks: 95

Roll No: 104
Name: Priya
Branch: CSE
Marks: 88



In [2]:
# Find the largest of three numbers

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a >= b and a >= c:
    largest = a
elif b >= a and b >= c:
    largest = b
else:
    largest = c

print("Largest number is:", largest)

Enter first number:  25
Enter second number:  15
Enter third number:  10


Largest number is: 25


In [3]:
# Check whether a triangle is right-angled

def right_triangle(a, b, c):
    sides = [a, b, c]
    sides.sort()

    if sides[0]**2 + sides[1]**2 == sides[2]**2:
        return True
    else:
        return False


a = float(input("Enter first side: "))
b = float(input("Enter second side: "))
c = float(input("Enter third side: "))

if right_triangle(a, b, c):
    print("It is a right-angled triangle")
else:
    print("It is not a right-angled triangle")

Enter first side:  3
Enter second side:  4
Enter third side:  5


It is a right-angled triangle


In [4]:
# Addition of two matrices

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Addition of matrices:")
print(C)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Addition of matrices:
[[ 6  8]
 [10 12]]


In [5]:
# PAN Number Validation

import re

pan = input("Enter PAN number: ")

pattern = r"^[A-Z]{5}[0-9]{4}[A-Z]$"

if re.match(pattern, pan):
    print("Valid PAN Number")
else:
    print("Invalid PAN Number")

Enter PAN number:  AAAPZ1234C


Valid PAN Number
